name: Release

on:
  release:
    types: [published]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: true
        token: ${{ secrets.ACCESS_TOKEN }}
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: 'Get tag'
      id: tag
      uses: "WyriHaximus/github-action-get-previous-tag@v1"
      with:
        fallback: 1.0.0
    #- name: Setup tmate session
    #  uses: mxschmitt/action-tmate@v3
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore Eto.Parse
    - name: Test
      run: dotnet test --no-build --verbosity normal Eto.Parse
    - name: Pack
      run: dotnet pack -p:PackageVersion=${{ steps.tag.outputs.tag }} --output nupkgs Eto.Parse
    - name: Publish
      run: dotnet nuget push nupkgs/*.nupkg -s "https://nuget.pkg.github.com/Tiplu/index.json" --api-key ${{ secrets.GITHUB_TOKEN }}
